const clothes = [
    { id: 1, name: "Футболка Staff & LBWS CAT2 дружба oversize", price: 490, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/b80bfefc0f774fb3adf39a152a963325.jpeg", gender: "male", category: "clothes", subcategory: "t-shirt", type: "t-shirt", available: true},
    { id: 2, name: "Футболка Staff & LBWS CAT2 ппо oversize", price: 490, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/e61341f735d54f0f8a61a9b2c2122ec4.jpeg", gender: "male", category: "clothes", subcategory: "t-shirt", type: "t-shirt", available: true},
    { id: 3, name: "Жіночий топ Staff ki c1", price: 380, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/17b32e8a5b004fc3826dc54417c30be6.jpeg", female: "male", category: "clothes", subcategory: "t-shirt",  type: "t-shirt", available: true},
    { id: 4, name: "Жіночий топ Staff hap blue", price: 390, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/4e37f16cd29a4f6890360e6051d8e21e.jpeg", gender: "female", category: "clothes", subcategory: "t-shirt",  type: "t-shirt", available: true},
    { id: 5, name: "Трикотажні шорти Staff khaki basic", price: 460, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/60/50f3ca87ca724fb091a4f55d471dd9ba.jpeg", gender: "male", category: "clothes", subcategory: "shorts",  type: "shorts",  available: true},
    { id: 6, name: "Трикотажні шорти Staff san dark beige", price: 520, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/60/d78accfa2baf4f60b77ea6df4f5ee55e.jpeg", gender: "male", category: "clothes", subcategory: "shorts",  type: "shorts",  available: true},
    { id: 7, name: "Жіночі шорти Staff basic black", price: 320, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/59/6989419cb36d4f68a54302956ad20d2d.jpeg", gender: "female", category: "clothes", subcategory: "shorts",  type: "shorts",  available: true},
    { id: 8, name: "Жіночі шорти Staff basic violet", price: 320, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/59/41fa0c6f25a64f02afdd9907195243c2.jpeg", gender: "female", category: "clothes", subcategory: "shorts",  type: "shorts",  available: true},
    { id: 9, name: "Комплект футболка + шорти Staff iv white & red", price: 570, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/57/4369ecb5cd764f5ebebd1c720cedc27f.jpeg", gender: "male", category: "clothes", subcategory: "set",  type: "set", available: true},
    { id: 10, name: "Комплект футболка + шорти Staff black logo", price: 630, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/57/61d23e4055f64f378c1858bb1e8f2960.jpeg", gender: "male", category: "clothes", subcategory: "set",  type: "set", available: true},
    { id: 11, name: "Труси Staff black/navy/graphite", price: 390, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/ee3a580e8be44ff1ae7b4faed8be6f8b.jpeg", gender: "male", category: "clothes", subcategory: "underwear",  type: "underwear", available: true},
    { id: 12, name: "Термобілизна Staff black2", price: 1150, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/73/dc9b1c748efc4f2b9db2ae22bb668721.png", gender: "male", category: "clothes", subcategory: "underwear",  type: "underwear", available: true},
    { id: 13, name: "Спортивний костюм Staff fg black oversize", price: 1140, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/a8bfa61ffec24f3cac0e64c6608f7e7f.jpeg", gender: "male", category: "clothes", subcategory: "tracksuits",  type: "tracksuits", available: true},
    { id: 14, name: "Спортивний костюм Staff intelock black & khaki", price: 1760, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/d354dfa4c8fa4f33b76b989ae9289625.jpeg", gender: "male", category: "clothes", subcategory: "tracksuits",  type: "tracksuits", available: true},
    { id: 15, name: "Лонгслів Staff & LBWS CAT2 наступ", price: 710, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/ba2ee51a68da4f63a9a15307829d5081.jpeg", gender: "male", category: "clothes", subcategory: "hoodies",  type: "hoodies", available: true},
    { id: 16, name: "Лонгслів Staff & LBWS CAT2 оборона", price: 710, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/76cc8f6b35394f20a44e305c2c7ab927.jpeg", gender: "male", category: "clothes", subcategory: "hoodies",  type: "hoodies", available: true},
    { id: 17, name: "Куртка Staff soft shell ny black & red", price: 1690, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/bb2ee494c5684f368808f92811b79fc3.jpeg", gender: "male", category: "clothes", subcategory: "outerwear",  type: "WINDSCREEN", available: true},
    { id: 18, name: "Тактична куртка Staff wind black", price: 1780, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/fb32457841144f87beac064e19064c5b.jpeg", gender: "male", category: "clothes", subcategory: "outerwear",  type: "WINDSCREEN", available: true},
    { id: 19, name: "Парка Staff us black", price: 1490, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/82/696cd6dea84e4f6e8a3f979b3ccadbc6.jpeg", gender: "male", category: "clothes", subcategory: "outerwear",  type: "autum-spring-parks", available: true},
    { id: 20, name: "Парка Staff us khaki", price: 1490 , photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/82/95ddebbe355a4f83a0de1361ae36e0d8.jpeg", gender: "male", category: "clothes", subcategory: "outerwear",  type: "autum-spring-parks", available: true},
    { id: 21, name: "Зимова тактична куртка Staff pixel2", price: 2100, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/76/0810017726564fdabf1624d4702adac8.jpeg", gender: "male", category: "clothes", subcategory: "outerwear",  type: "winter_jackets", available: true},
    { id: 22, name: "Джинси Staff odw c4 slim", price: 1090, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/db88e7f680304fd9b8984231b8146f94.jpeg", gender: "male", category: "clothes", subcategory: "pants",  type: "jeans", available: true},
    { id: 23, name: "Джинси Staff loo black2 slim", price: 1090, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/de5f13fbcac84f648cd64244d001a1b4.jpeg", gender: "male", category: "clothes", subcategory: "pants",  type: "jeans", available: true},
    { id: 24, name: "Спортивні штани Staff green gray basic", price: 820, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/8706b1e892304f79a13b5cc28aa61861.jpeg", gender: "male", category: "clothes", subcategory: "pants",  type: "sport_pants", available: true},
    { id: 25, name: "Спортивні штани Staff brown basic", price: 850, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/87/9a83f234448e4f37889a9dc19242b1a1.jpeg", gender: "male", category: "clothes", subcategory: "pants",  type: "sport_pants", available: true},
    { id: 26, name: "Штани Staff cargo gray square", price: 1090, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/5efec61882564f08b53bd41cdebb0ac4.jpeg", gender: "male", category: "clothes", subcategory: "pants",  type: "cargo_jogers_chinos", available: true},
    { id: 27, name: "Штани Staff cargo SJ black", price: 990, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/39dc541991a14f6187c4573d7d91f69a.jpeg", gender: "male", category: "clothes", subcategory: "pants",  type: "cargo_jogers_chinos", available: true},

    { id: 28, name: "Зимові кросівки Staff black modern", price: 2500, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/75/2fc136a1c1a44fd996c3f124945b4656.jpeg", gender: "male", category: "shoe", subcategory: "winter_shoe",  type: "winter_shoe", available: true},
    { id: 29, name: "Тактичні черевики Staff camo pixel", price: 1860, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/62/0dfdec43ddd64f419ef11b290e3a83fb.jpeg", gender: "male", category: "shoe", subcategory: "winter_shoe",  type: "winter_shoe", available: true},
    { id: 30, name: "Кросівки Staff black & dark gray", price: 1990, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/1e6b008597a84f1998b5a4801978b366.jpeg", gender: "male", category: "shoe", subcategory: "sneakers",  type: "sneakers", available: true},
    { id: 31, name: "Кросівки Staff black & dark gray & haki", price: 1990, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/20a33d519a3b4f8da8230e2850442fbe.jpeg", gender: "male", category: "shoe", subcategory: "sneakers",  type: "sneakers", available: true},


    { id: 32, name: "Рюкзак Staff roll 25L black & khaki", price: 750, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/731b9f062ed04fc2b9fe1f413f32ec20.jpeg", gender: "male", category: "backpacks_and_bags", subcategory: "backpacks",  type: "backpacks", available: true},
    { id: 33, name: "Рюкзак Staff rolltop 24L all black", price: 790, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/ad4532a56e604f8188d81d6c0d7b47b2.jpeg", gender: "male", category: "backpacks_and_bags", subcategory: "backpacks",  type: "backpacks", available: true},
    { id: 34, name: "Спортивна сумка Staff black logo", price: 690, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/debf787fb53b4fad8c0d11594b06ae01.jpeg", gender: "male", category: "backpacks_and_bags", subcategory: "belt_bags",  type: "shoulder_bags", available: true},
    { id: 35, name: "Сумка через плече Staff black & gray camo", price: 390, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/87/41470c6258104f448a63fc06a0cf68a2.jpeg", gender: "male", category: "backpacks_and_bags", subcategory: "belt_bags",  type: "belt_bags", available: true},
    { id: 36, name: "Поясна сумка Staff leather white", price: 370, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/78/58395ab805914f00a4da9c2290fce59a.jpeg", gender: "male", category: "backpacks_and_bags", subcategory: "belt_bags",  type: "belt_bags", available: true},
    { id: 37, name: "Поясна сумка Staff navy", price: 370, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/62/5d5115e5367e4fd4b0368752b7098fa0.jpeg", gender: "male", category: "backpacks_and_bags", subcategory: "belt_bags",  type: "belt_bags", available: true},



    { id: 38, name: "Панама Staff fo", price: 350, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/ffb3130ae18c4f4a87817b5cc64adfe5.jpeg", gender: "male", category: "accessories", subcategory: "caps_panamas",  type: "caps_panamas", available: true},
    { id: 39, name: "Панама Staff money", price: 350, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/356fbed5031a4fc7808584d29d18fde3.jpeg", gender: "male", category: "accessories", subcategory: "caps_panamas",  type: "caps_panamas", available: true},
    { id: 40, name: "Шапка Staff black & beige", price: 270, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/77/56c80dae57e54f1384b5d74b478cdada.jpeg", gender: "male", category: "accessories", subcategory: "winter_hats",  type: "winter_hats", available: true},
    { id: 41, name: "Шапка Staff mountains2", price: 270, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/76/52ed498a9b504faa83d397c2d42ed784.jpeg", gender: "male", category: "accessories", subcategory: "winter_hats",  type: "winter_hats", available: true},
    { id: 42, name: "Багаторазова маска Staff black", price: 50, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/46/6fa5b9e7bb7f4fd1bbdd5c2a7014540b.jpeg", gender: "male", category: "accessories", subcategory: "scarves_gloves",  type: "scarves_gloves", available: true},
    { id: 43, name: "Багаторазова маска Staff white", price: 50, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/46/d1b829d6dcd34f2b8b31024f4624b7b1.jpeg", gender: "male", category: "accessories", subcategory: "scarves_gloves",  type: "scarves_gloves", available: true},
    { id: 44, name: "Шкарпетки Staff gray/black/white (три пари)", price: 149, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/37eb0d9afc6f4fd8a7987ae6f4bb10c8.jpeg", gender: "male", category: "accessories", subcategory: "socks",  type: "socks", available: true},
    { id: 45, name: "Шкарпетки Staff gray & white", price: 40, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/23050615e1704fb0a0fb0b2272498abd.jpeg", gender: "male", category: "accessories", subcategory: "socks",  type: "socks", available: true},
    { id: 46, name: "Ремінь Staff cord Full\n\n", price: 240, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/5bfa500f52ec4f148bcc439031dfbbe4.jpeg", gender: "male", category: "accessories", subcategory: "belts_glasses_stickers_wallets",  type: "belts_glasses_stickers_wallets", available: true},
    { id: 47, name: "Гаманець Staff black", price: 140, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/84/363ef306de9f4fe5807e8f402782f015.jpeg", gender: "male", category: "accessories", subcategory: "belts_glasses_stickers_wallets",  type: "belts_glasses_stickers_wallets", available: true},


];


// const example = {
//     id: 1,
//     name: "",
//     price: 2222,
//     photo: "",
//     gender: "male/famale",
//     category: "t-shirt",
//     type: "",
//     available: true
// }

// const empty =
// { id: , name: "", price: , photo: "", gender: "male/famale", category: "", subcategory: "",  type: "", available: }