const clothes = [
    { id: 1, name: "Футболка Staff & LBWS CAT2 дружба oversize", price: 490, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/b80bfefc0f774fb3adf39a152a963325.jpeg", gender: "male", category: "clothes", subcategory: "t-shirt", type: "t-shirt", available: true},
    { id: 2, name: "Футболка Staff & LBWS CAT2 ппо oversize", price: 490, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/e61341f735d54f0f8a61a9b2c2122ec4.jpeg", gender: "male", category: "clothes", subcategory: "t-shirt", type: "t-shirt", available: true},
    { id: 3, name: "Жіночий топ Staff ki c1", price: 380, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/17b32e8a5b004fc3826dc54417c30be6.jpeg", female: "male", category: "clothes", subcategory: "t-shirt",  type: "t-shirt", available: true},
    { id: 4, name: "Жіночий топ Staff hap blue", price: 390, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/4e37f16cd29a4f6890360e6051d8e21e.jpeg", gender: "female", category: "clothes", subcategory: "t-shirt",  type: "t-shirt", available: true},
    { id: 5, name: "Трикотажні шорти Staff khaki basic", price: 460, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/60/50f3ca87ca724fb091a4f55d471dd9ba.jpeg", gender: "male", category: "clothes", subcategory: "shorts",  type: "shorts",  available: true},
    { id: 6, name: "Трикотажні шорти Staff san dark beige", price: 520, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/60/d78accfa2baf4f60b77ea6df4f5ee55e.jpeg", gender: "male", category: "clothes", subcategory: "shorts",  type: "shorts",  available: true},
    { id: 7, name: "Жіночі шорти Staff basic black", price: 320, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/59/6989419cb36d4f68a54302956ad20d2d.jpeg", gender: "female", category: "clothes", subcategory: "shorts",  type: "shorts",  available: true},
    { id: 8, name: "Жіночі шорти Staff basic violet", price: 320, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/59/41fa0c6f25a64f02afdd9907195243c2.jpeg", gender: "female", category: "clothes", subcategory: "shorts",  type: "shorts",  available: true},
    { id: 9, name: "Комплект футболка + шорти Staff iv white & red", price: 570, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/57/4369ecb5cd764f5ebebd1c720cedc27f.jpeg", gender: "male", category: "clothes", subcategory: "set",  type: "set", available: true},
    { id: 10, name: "Комплект футболка + шорти Staff black logo", price: 630, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/57/61d23e4055f64f378c1858bb1e8f2960.jpeg", gender: "male", category: "clothes", subcategory: "set",  type: "set", available: true},
    { id: 11, name: "Труси Staff black/navy/graphite", price: 390, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/ee3a580e8be44ff1ae7b4faed8be6f8b.jpeg", gender: "male", category: "clothes", subcategory: "underwear",  type: "underwear", available: true},
    { id: 12, name: "Термобілизна Staff black2", price: 1150, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/73/dc9b1c748efc4f2b9db2ae22bb668721.png", gender: "male", category: "clothes", subcategory: "underwear",  type: "underwear", available: true},
    { id: 13, name: "Спортивний костюм Staff fg black oversize", price: 1140, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/a8bfa61ffec24f3cac0e64c6608f7e7f.jpeg", gender: "male", category: "clothes", subcategory: "tracksuits",  type: "tracksuits", available: true},
    { id: 14, name: "Спортивний костюм Staff intelock black & khaki", price: 1760, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/d354dfa4c8fa4f33b76b989ae9289625.jpeg", gender: "male", category: "clothes", subcategory: "tracksuits",  type: "tracksuits", available: true},
    { id: 15, name: "Лонгслів Staff & LBWS CAT2 наступ", price: 710, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/ba2ee51a68da4f63a9a15307829d5081.jpeg", gender: "male", category: "clothes", subcategory: "hoodies",  type: "hoodies", available: true},
    { id: 16, name: "Лонгслів Staff & LBWS CAT2 оборона", price: 710, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/76cc8f6b35394f20a44e305c2c7ab927.jpeg", gender: "male", category: "clothes", subcategory: "hoodies",  type: "hoodies", available: true},
    { id: 17, name: "Куртка Staff soft shell ny black & red", price: 1690, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/bb2ee494c5684f368808f92811b79fc3.jpeg", gender: "male", category: "clothes", subcategory: "outerwear",  type: "WINDSCREEN", available: true},
    { id: 18, name: "Тактична куртка Staff wind black", price: 1780, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/fb32457841144f87beac064e19064c5b.jpeg", gender: "male", category: "clothes", subcategory: "outerwear",  type: "WINDSCREEN", available: true},
    { id: 19, name: "Парка Staff us black", price: 1490, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/82/696cd6dea84e4f6e8a3f979b3ccadbc6.jpeg", gender: "male", category: "clothes", subcategory: "outerwear",  type: "autum-spring-parks", available: true},
    { id: 20, name: "Парка Staff us khaki", price: 1490 , photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/82/95ddebbe355a4f83a0de1361ae36e0d8.jpeg", gender: "male", category: "clothes", subcategory: "outerwear",  type: "autum-spring-parks", available: true},
    { id: 21, name: "Зимова тактична куртка Staff pixel2", price: 2100, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/76/0810017726564fdabf1624d4702adac8.jpeg", gender: "male", category: "clothes", subcategory: "outerwear",  type: "winter_jackets", available: true},
    { id: 22, name: "Джинси Staff odw c4 slim", price: 1090, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/db88e7f680304fd9b8984231b8146f94.jpeg", gender: "male", category: "clothes", subcategory: "pants",  type: "jeans", available: true},
    { id: 23, name: "Джинси Staff loo black2 slim", price: 1090, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/de5f13fbcac84f648cd64244d001a1b4.jpeg", gender: "male", category: "clothes", subcategory: "pants",  type: "jeans", available: true},
    { id: 24, name: "Спортивні штани Staff green gray basic", price: 820, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/8706b1e892304f79a13b5cc28aa61861.jpeg", gender: "male", category: "clothes", subcategory: "pants",  type: "sport_pants", available: true},
    { id: 25, name: "Спортивні штани Staff brown basic", price: 850, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/87/9a83f234448e4f37889a9dc19242b1a1.jpeg", gender: "male", category: "clothes", subcategory: "pants",  type: "sport_pants", available: true},
    { id: 26, name: "Штани Staff cargo gray square", price: 1090, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/5efec61882564f08b53bd41cdebb0ac4.jpeg", gender: "male", category: "clothes", subcategory: "pants",  type: "cargo_jogers_chinos", available: true},
    { id: 27, name: "Штани Staff cargo SJ black", price: 990, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/39dc541991a14f6187c4573d7d91f69a.jpeg", gender: "male", category: "clothes", subcategory: "pants",  type: "cargo_jogers_chinos", available: true},

    { id: 28, name: "Зимові кросівки Staff black modern", price: 2500, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/75/2fc136a1c1a44fd996c3f124945b4656.jpeg", gender: "male", category: "shoe", subcategory: "winter_shoe",  type: "winter_shoe", available: true},
    { id: 29, name: "Тактичні черевики Staff camo pixel", price: 1860, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/62/0dfdec43ddd64f419ef11b290e3a83fb.jpeg", gender: "male", category: "shoe", subcategory: "winter_shoe",  type: "winter_shoe", available: true},
    { id: 30, name: "Кросівки Staff black & dark gray", price: 1990, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/1e6b008597a84f1998b5a4801978b366.jpeg", gender: "male", category: "shoe", subcategory: "sneakers",  type: "sneakers", available: true},
    { id: 31, name: "Кросівки Staff black & dark gray & haki", price: 1990, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/20a33d519a3b4f8da8230e2850442fbe.jpeg", gender: "male", category: "shoe", subcategory: "sneakers",  type: "sneakers", available: true},


    { id: 32, name: "Рюкзак Staff roll 25L black & khaki", price: 750, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/731b9f062ed04fc2b9fe1f413f32ec20.jpeg", gender: "male", category: "backpacks_and_bags", subcategory: "backpacks",  type: "backpacks", available: true},
    { id: 33, name: "Рюкзак Staff rolltop 24L all black", price: 790, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/ad4532a56e604f8188d81d6c0d7b47b2.jpeg", gender: "male", category: "backpacks_and_bags", subcategory: "backpacks",  type: "backpacks", available: true},
    { id: 34, name: "Спортивна сумка Staff black logo", price: 690, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/debf787fb53b4fad8c0d11594b06ae01.jpeg", gender: "male", category: "backpacks_and_bags", subcategory: "shoulder_bags",  type: "shoulder_bags", available: true},
    { id: 35, name: "Сумка через плече Staff black & gray camo", price: 390, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/87/41470c6258104f448a63fc06a0cf68a2.jpeg", gender: "male", category: "backpacks_and_bags", subcategory: "shoulder_bags",  type: "shoulder_bags", available: true},
    { id: 36, name: "Поясна сумка Staff leather white", price: 370, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/78/58395ab805914f00a4da9c2290fce59a.jpeg", gender: "male", category: "backpacks_and_bags", subcategory: "belt_bags",  type: "belt_bags", available: true},
    { id: 37, name: "Поясна сумка Staff navy", price: 370, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/62/5d5115e5367e4fd4b0368752b7098fa0.jpeg", gender: "male", category: "backpacks_and_bags", subcategory: "belt_bags",  type: "belt_bags", available: true},



    { id: 38, name: "Панама Staff fo", price: 350, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/ffb3130ae18c4f4a87817b5cc64adfe5.jpeg", gender: "male", category: "accessories", subcategory: "caps_panamas",  type: "caps_panamas", available: true},
    { id: 39, name: "Панама Staff money", price: 350, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/356fbed5031a4fc7808584d29d18fde3.jpeg", gender: "male", category: "accessories", subcategory: "caps_panamas",  type: "caps_panamas", available: true},
    { id: 40, name: "Шапка Staff black & beige", price: 270, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/77/56c80dae57e54f1384b5d74b478cdada.jpeg", gender: "male", category: "accessories", subcategory: "winter_hats",  type: "winter_hats", available: true},
    { id: 41, name: "Шапка Staff mountains2", price: 270, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/76/52ed498a9b504faa83d397c2d42ed784.jpeg", gender: "male", category: "accessories", subcategory: "winter_hats",  type: "winter_hats", available: true},
    { id: 42, name: "Багаторазова маска Staff black", price: 50, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/46/6fa5b9e7bb7f4fd1bbdd5c2a7014540b.jpeg", gender: "male", category: "accessories", subcategory: "scarves_gloves",  type: "scarves_gloves", available: true},
    { id: 43, name: "Багаторазова маска Staff white", price: 50, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/46/d1b829d6dcd34f2b8b31024f4624b7b1.jpeg", gender: "male", category: "accessories", subcategory: "scarves_gloves",  type: "scarves_gloves", available: true},
    { id: 44, name: "Шкарпетки Staff gray/black/white (три пари)", price: 149, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/37eb0d9afc6f4fd8a7987ae6f4bb10c8.jpeg", gender: "male", category: "accessories", subcategory: "socks",  type: "socks", available: true},
    { id: 45, name: "Шкарпетки Staff gray & white", price: 40, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/23050615e1704fb0a0fb0b2272498abd.jpeg", gender: "male", category: "accessories", subcategory: "socks",  type: "socks", available: true},
    { id: 46, name: "Ремінь Staff cord Full\n\n", price: 240, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/5bfa500f52ec4f148bcc439031dfbbe4.jpeg", gender: "male", category: "accessories", subcategory: "belts_glasses_stickers_wallets",  type: "belts_glasses_stickers_wallets", available: true},
    { id: 47, name: "Гаманець Staff black", price: 140, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/84/363ef306de9f4fe5807e8f402782f015.jpeg", gender: "male", category: "accessories", subcategory: "belts_glasses_stickers_wallets",  type: "belts_glasses_stickers_wallets", available: true},



//     female

    { id: 48, name: "Жіноча куртка Staff soft shell black", price: 1390, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/70a107e8cf1d4f9a916d059f475341c1.jpeg", gender: "female", category: "clothes", subcategory: "outerwear",  type: "WINDSCREEN", available: true},
    { id: 49, name: "Жіноча куртка-сорочка Staff c2", price: 1090, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/a9c7be45ca9b4fd7af2810b071c249c6.jpeg", gender: "female", category: "clothes", subcategory: "outerwear",  type: "WINDSCREEN", available: true},
    { id: 50, name: "Жіноча парка куртка Staff ni black", price: 2750, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/73/6c8ac0e60a384fad90ecd0b2f42bcda7.jpeg", gender: "female", category: "clothes", subcategory: "outerwear",  type: "winter_parks", available: true},
    { id: 51, name: "Жіноча екошуба Staff beige", price: 2590, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/72/7565bb88f2ed4f55b576d6e64b8b4d89.jpeg", gender: "female", category: "clothes", subcategory: "outerwear",  type: "coats", available: true},
    { id: 52, name: "Жіноча зимова куртка Staff jo black", price: 2200, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/78/161b46e3afbc4fb58e8f85e119d69204.jpeg", gender: "female", category: "clothes", subcategory: "outerwear",  type: "winter_jackets", available: true},



    { id: 53, name: "Жіноча толстовка Staff black logo oversize", price: 630, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/86/1879acc1b4a74f089925851de4f94450.jpeg", gender: "female", category: "clothes", subcategory: "hoodies",  type: "hoodies", available: true},
    { id: 54, name: "Жіночий світшот Staff logo & fire oversize", price: 880, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/8aa231d72d904f0998eaf1e1c7d33751.jpeg", gender: "female", category: "clothes", subcategory: "hoodies",  type: "hoodies", available: true},


    { id: 54, name: "Жіночий світшот Staff logo & fire oversize", price: 880, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/8aa231d72d904f0998eaf1e1c7d33751.jpeg", gender: "female", category: "clothes", subcategory: "hoodies",  type: "hoodies", available: true},


    { id: 55, name: "Боді Staff pink camo", price: 540, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/86/c7f907694ef64f29bcca36f5d9112ec5.jpeg", gender: "female", category: "clothes", subcategory: "body",  type: "body", available: true},
    { id: 56, name: "Боді Staff beige", price: 590, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/89/3652f00cf7424fa1b875013653bd6260.jpeg", gender: "female", category: "clothes", subcategory: "body",  type: "body", available: true},

    { id: 57, name: "Жіночі спортивні штани Staff di gray", price: 580, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/85/7d4bdcdc20df4fc08bb6611cd38b9922.jpeg", gender: "female", category: "clothes", subcategory: "pants",  type: "pants", available: true},
    { id: 58, name: "Жіночі спортивні штани Staff di black", price: 590, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/86/7adb2069a4394f138c2d6576b6679b0c.jpeg", gender: "female", category: "clothes", subcategory: "pants",  type: "pants", available: true},

    { id: 59, name: "Жіночий спортивний костюм Staff el milk oversize", price: 1470, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/8f59e28bb8404fe1ad5c5e2e5724e387.jpeg", gender: "female", category: "clothes", subcategory: "tracksuits",  type: "tracksuits", available: true},
    { id: 60, name: "Жіночий спортивний костюм Staff ice pink", price: 1490, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/88/904273b0ec3a4f7daf789c11d7ce1b5f.jpeg", gender: "female", category: "clothes", subcategory: "tracksuits",  type: "tracksuits", available: true},


    { id: 61, name: "Жіночий літній костюм Staff bam beige", price: 430, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/59/2a7747a4b1744fe2bf5e1e9e4b464fc1.jpeg", gender: "female", category: "clothes", subcategory: "set",  type: "set", available: true},



    { id: 62, name: "Сукня Staff er gray", price: 590, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/c33e23a353434f3d834b9017c5e93cc1.jpeg", gender: "female", category: "clothes", subcategory: "dress",  type: "dress", available: true},
    { id: 63, name: "Сукня Staff er beige", price: 590, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/3bcc5b1f7c774f3a8dfbf52a50d9ddf0.jpeg", gender: "female", category: "clothes", subcategory: "dress",  type: "dress", available: true},

    { id: 64, name: "Купальник Staff basic white", price: 370, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/53/0d121bf1d9524f13a981f620bd75a3c1.jpeg", gender: "female", category: "clothes", subcategory: "swimwear",  type: "swimwear", available: true},
    { id: 65, name: "Купальник Staff s white", price: 380, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/58/a8d5f91659ab4f6dac85af169bea214b.jpeg", gender: "female", category: "clothes", subcategory: "swimwear",  type: "swimwear", available: true},

    { id: 66, name: "Жіночий костюм Staff me black & white", price: 1330, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/90/5bcdd027d3bf4f13aaeee314c6c4a5f2.jpeg", gender: "female", category: "clothes", subcategory: "suits",  type: "suits", available: true},


    { id: 67, name: "Жіночі черевики Staff black", price: 2070, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/70/40c3a52183a84f9fb6b9efb8ba0e6fc6.jpeg", gender: "female", category: "shoe", subcategory: "winter_shoe",  type: "winter_shoe", available: true},
    { id: 68, name: "Жіночі кеди Staff pink", price: 760, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/64/1432f884f6304fa397ad984650a79cb9.jpeg", gender: "female", category: "shoe", subcategory: "sneakers",  type: "sneakers", available: true},
    { id: 69, name: "Жіночі кросівки Staff black", price: 1380, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/82/9e381f0cd1814fa39e9034509e60df75.jpeg", gender: "female", category: "shoe", subcategory: "sneakers",  type: "sneakers", available: true},

    { id: 70, name: "Жіночий рюкзак Staff am velor dark gray", price: 690, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/86/c6dbe10daf1f4f9784bfa4ff5ec0ca2e.jpeg", gender: "female", category: "accessories", subcategory: "backpacks",  type: "backpacks", available: true},
    { id: 71, name: "Жіночий рюкзак Staff am velor black", price: 670, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/86/80cbeaacee774fda8d16a58f331a5051.jpeg", gender: "female", category: "accessories", subcategory: "backpacks",  type: "backpacks", available: true},
    { id: 72, name: "Поясна сумка Staff rose", price: 350, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/56/400f3b8db60f4f6796f610aa22f8d531.jpeg", gender: "female", category: "accessories", subcategory: "belt_bags",  type: "belt_bags", available: true},
    { id: 73, name: "Поясна сумка Staff flower", price: 360, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/59/96084dc3dfbb4f3db12465373945f168.jpeg", gender: "female", category: "accessories", subcategory: "belt_bags",  type: "belt_bags", available: true},
    { id: 74, name: "Сумка шоппер Staff leather black", price: 700, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/55/f4ec63f1134d4fa496d1f7b54022aa0a.jpeg", gender: "female", category: "accessories", subcategory: "shoulder_bags",  type: "shoulder_bags", available: true},
    { id: 75, name: "Жіночі шкарпетки Staff white & black", price: 60, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/83/6fc639a727734f76b0b3748f33f97da9.jpeg", gender: "female", category: "accessories", subcategory: "socks",  type: "socks", available: true},
    { id: 76, name: "Жіночі шкарпетки Staff butterflies", price: 60, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/83/699238dcdba84f9a9fa14f89f59d1ac3.jpeg", gender: "female", category: "accessories", subcategory: "socks",  type: "socks", available: true},
    { id: 77, name: "Жіноча шапка Staff pompon beige", price: 260, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/74/26b676efbc224f828e5592b050c4ec23.jpeg", gender: "female", category: "accessories", subcategory: "winter_hats",  type: "winter_hats", available: true},
    { id: 78, name: "Шапка Staff pompon peach", price: 260, photo: "https://static.staff-clothes.com/media/cache/image_product_desktop_product_thumbnail/image_product/0002/73/732b089a44444f91927733cf7365624f.jpeg", gender: "female", category: "accessories", subcategory: "winter_hats",  type: "winter_hats", available: true},


//        { id: , name: "", price: , photo: "", gender: "female", category: "", subcategory: "",  type: "", available: },

];


// const example = {
//     id: 1,
//     name: "",
//     price: 2222,
//     photo: "",
//     gender: "male/famale",
//     category: "t-shirt",
//     type: "",
//     available: true
// }

// const empty =
// { id: , name: "", price: , photo: "", gender: "male/famale", category: "", subcategory: "",  type: "", available: }